### ISSUE TITLE
District Boundary Lookup API Call causes Django error on openstates.org site

### ISSUE THREAD

**Issue by dogebytes** [sunlightlabs/billy#258]
Hello,  
  
While trying to visualize API method calls manually, I found that the boundary lookup URL causes an error.  
  
Error causing call:  
`http://openstates.org/api/v1/districts/boundary/sldl/nc-120/?apikey=ThisWasAKnownGoodKey`

Result:  
```Piston/0.2.3rc1 (Django 1.6.2) crash report: Traceback (most recent call last): File "/projects/openstates/virt/src/billy/billy/web/api/handlers.py", line 89, in new_read obj = old_read(*args, **kwargs) File "/projects/openstates/virt/src/billy/billy/web/api/handlers.py", line 508, in read resp = rc.NOT_FOUND File "/projects/openstates/virt/src/django-piston/piston/utils.py", line 55, in __getattr__ class HttpResponseWrapper(HttpResponse): File "/projects/openstates/virt/src/django-piston/piston/utils.py", line 82, in HttpResponseWrapper content = property(HttpResponse._get_content, _set_content) AttributeError: type object 'HttpResponse' has no attribute '_get_content'```

**Comment by paultag** [comment]
Yeah, this is the same as #248 - should be set in a few hours when I redeploy

Thanks!

**Comment by dogebytes** [comment]
@paultag Sorry for the dupe.  I appreciate your efforts.

**Comment by paultag** [comment]
Hey man, no worries! Thanks for the report!
